// GENERATED by scripts/generate-seed-manifest.ts — do not edit by hand.
//
// Fingerprint of the retired bundled starter seed (Ralph's April 2026 iPad
// export that older binaries planted into every fresh install). Used by
// lib/db/seedCleanup.ts to identify and remove starter rows that the device's
// user never touched. ids + updated_at stamps only; the full seed data lives
// in assets/seeds/initial-seed.json (kept in the repo, no longer bundled).

export type SeedPiece = {
  id: string;
  updated_at: number | null;
  files: string[];
  exercises: { id: string; updated_at: number | null }[];
};

export const SEED_PIECES: SeedPiece[] = [
  {
    "id": "1777140679580-whoy6me0",
    "updated_at": 1777422903441,
    "files": [
      "1777140679580-whoy6me0.1777209794231.jpg",
      "1777140679580-whoy6me0.1777209794231.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140679580-whoy6me0:tempo_ladder",
        "updated_at": 1777140687264
      },
      {
        "id": "1777140679580-whoy6me0:click_up",
        "updated_at": 1777422906743
      },
      {
        "id": "e_1777209808439_7854tq",
        "updated_at": 1777209814838
      }
    ]
  },
  {
    "id": "1777140712287-bmthwn7l",
    "updated_at": 1777140721478,
    "files": [
      "1777140712287-bmthwn7l.1777140718875.jpg",
      "1777140712287-bmthwn7l.1777140718875.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140712287-bmthwn7l:tempo_ladder",
        "updated_at": 1777146193912
      },
      {
        "id": "e_1777340444271_y48clk",
        "updated_at": 1777340471112
      },
      {
        "id": "e_1777340484665_ilhkpf",
        "updated_at": 1777422234243
      },
      {
        "id": "1777140712287-bmthwn7l:click_up",
        "updated_at": 1777422571987
      }
    ]
  },
  {
    "id": "1777140724277-8cm2t3ps",
    "updated_at": 1777421233761,
    "files": [
      "1777140724277-8cm2t3ps.1777140728534.jpg",
      "1777140724277-8cm2t3ps.1777140728534.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140724277-8cm2t3ps:tempo_ladder",
        "updated_at": 1777140734322
      },
      {
        "id": "e_1777206544019_qhkwlv",
        "updated_at": 1777340638782
      },
      {
        "id": "e_1777206659217_b6zoea",
        "updated_at": 1777340641330
      },
      {
        "id": "e_1777340643575_xhbevq",
        "updated_at": 1777340652750
      },
      {
        "id": "e_1777340654653_veiq7e",
        "updated_at": 1777422186533
      },
      {
        "id": "1777140724277-8cm2t3ps:click_up",
        "updated_at": 1777421235880
      }
    ]
  },
  {
    "id": "1777140762174-zgpb2zeg",
    "updated_at": 1777145474931,
    "files": [
      "1777140762174-zgpb2zeg.1777140772702.jpg",
      "1777140762174-zgpb2zeg.1777140772702.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140762174-zgpb2zeg:tempo_ladder",
        "updated_at": 1777141438766
      },
      {
        "id": "1777140762174-zgpb2zeg:click_up",
        "updated_at": 1777145477035
      }
    ]
  },
  {
    "id": "1777140778987-swdtebvk",
    "updated_at": 1777394223671,
    "files": [
      "1777140778987-swdtebvk.1777140787536.jpg",
      "1777140778987-swdtebvk.1777140787536.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140778987-swdtebvk:tempo_ladder",
        "updated_at": 1777146196933
      },
      {
        "id": "1777140778987-swdtebvk:click_up",
        "updated_at": 1777394225547
      },
      {
        "id": "e_1777394263500_syxtb9",
        "updated_at": 1777394264031
      }
    ]
  },
  {
    "id": "1777140792700-0ob2uxh6",
    "updated_at": 1777140806691,
    "files": [
      "1777140792700-0ob2uxh6.1777140803597.jpg",
      "1777140792700-0ob2uxh6.1777140803597.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140792700-0ob2uxh6:tempo_ladder",
        "updated_at": 1777220410697
      }
    ]
  },
  {
    "id": "1777140808558-lmjwffzi",
    "updated_at": 1777140817355,
    "files": [
      "1777140808558-lmjwffzi.1777140814510.jpg",
      "1777140808558-lmjwffzi.1777140814510.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140808558-lmjwffzi:tempo_ladder",
        "updated_at": 1777140820732
      },
      {
        "id": "e_1777147051821_zknscc",
        "updated_at": 1777339125255
      }
    ]
  },
  {
    "id": "1777140931386-zkrr6kew",
    "updated_at": 1777140944949,
    "files": [
      "1777140931386-zkrr6kew.jpg",
      "1777140931386-zkrr6kew.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140931386-zkrr6kew:tempo_ladder",
        "updated_at": 1777140945106
      },
      {
        "id": "e_1777222287911_fa9805",
        "updated_at": 1777222368278
      }
    ]
  },
  {
    "id": "1777140986550-w1hyo97e",
    "updated_at": 1777211147887,
    "files": [
      "1777140986550-w1hyo97e.1777140996563.jpg",
      "1777140986550-w1hyo97e.1777140996563.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777140986550-w1hyo97e:tempo_ladder",
        "updated_at": 1777150318276
      },
      {
        "id": "1777140986550-w1hyo97e:click_up",
        "updated_at": 1777211177581
      },
      {
        "id": "e_1777221240134_8a1it9",
        "updated_at": 1777221371183
      }
    ]
  },
  {
    "id": "1777141002737-iniauk9n",
    "updated_at": 1777205019737,
    "files": [
      "1777141002737-iniauk9n.1777141016524.jpg",
      "1777141002737-iniauk9n.1777141016524.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777141002737-iniauk9n:tempo_ladder",
        "updated_at": 1777141022341
      },
      {
        "id": "1777141002737-iniauk9n:click_up",
        "updated_at": 1777205021383
      },
      {
        "id": "e_1777221801011_3hmseb",
        "updated_at": 1777221843474
      }
    ]
  },
  {
    "id": "1777141047900-49tiptku",
    "updated_at": 1777141065725,
    "files": [
      "1777141047900-49tiptku.1777141063010.jpg",
      "1777141047900-49tiptku.1777141063010.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777141047900-49tiptku:tempo_ladder",
        "updated_at": 1777141067622
      },
      {
        "id": "e_1777211926156_fw88zd",
        "updated_at": 1777211968969
      }
    ]
  },
  {
    "id": "1777308321730-k01sfsvp",
    "updated_at": 1777398296138,
    "files": [
      "file:///var/mobile/Containers/Data/Application/E1EDEC41-0DD6-40D1-9F28-52A1D0739DF5/Documents/pieces/1777308321730-k01sfsvp.1777308340788.jpg",
      "file:///var/mobile/Containers/Data/Application/E1EDEC41-0DD6-40D1-9F28-52A1D0739DF5/Documents/pieces/1777308321730-k01sfsvp.1777308340788.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777308321730-k01sfsvp:tempo_ladder",
        "updated_at": 1777308349826
      },
      {
        "id": "1777308321730-k01sfsvp:click_up",
        "updated_at": 1777308652606
      }
    ]
  },
  {
    "id": "1777402474871-bqfqswp9",
    "updated_at": 1777421080782,
    "files": [
      "1777402474871-bqfqswp9.1777402478638.jpg",
      "1777402474871-bqfqswp9.1777402478638.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777402474871-bqfqswp9:tempo_ladder",
        "updated_at": 1777402487099
      },
      {
        "id": "e_1777402493542_7s3waz",
        "updated_at": 1777403260414
      }
    ]
  },
  {
    "id": "1777403016055-ur15ie31",
    "updated_at": 1777421083420,
    "files": [
      "1777403016055-ur15ie31.1777403018310.jpg",
      "1777403016055-ur15ie31.1777403018310.thumb.jpg"
    ],
    "exercises": [
      {
        "id": "1777403016055-ur15ie31:tempo_ladder",
        "updated_at": 1777403025459
      },
      {
        "id": "e_1777403030730_shqil0",
        "updated_at": 1777403223535
      }
    ]
  }
];

export const SEED_FOLDERS: { id: string; updated_at: number | null }[] = [
  {
    "id": "f_1777140595690_2rnjur",
    "updated_at": 1777140595690
  },
  {
    "id": "f_1777421069421_nwxr23",
    "updated_at": 1777421069421
  }
];

export const SEED_PRACTICE_LOG_IDS: number[] = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58
];

export const SEED_SETTINGS: { key: string; value_json: string }[] = [
  {
    "key": "strategy_colors",
    "value_json": "\"{\\\"tempo_ladder\\\":\\\"#2ecc71\\\",\\\"click_up\\\":\\\"#f39c12\\\",\\\"rhythmic\\\":\\\"#4a235a\\\",\\\"interleaved\\\":\\\"#7b2d00\\\"}\""
  },
  {
    "key": "folder_tip_shown",
    "value_json": "\"true\""
  },
  {
    "key": "timers.microbreak",
    "value_json": "\"{\\\"enabled\\\":true,\\\"breakSeconds\\\":12}\""
  },
  {
    "key": "last_used_instrument_id",
    "value_json": "\"concert\""
  },
  {
    "key": "last_used_grouping",
    "value_json": "\"6\""
  }
];
