// Regenerates lib/db/seedManifest.ts from assets/seeds/initial-seed.json.
//
// The manifest is the small (few-KB) fingerprint of the retired bundled
// starter seed — just ids + updated_at stamps + file basenames — that
// lib/db/seedCleanup.ts uses to remove untouched starter content from
// installs that were seeded by older binaries. The 5.7MB seed JSON itself is
// no longer imported anywhere, so it stays out of the app bundle; this script
// exists so the manifest can be rebuilt if the seed file ever changes.
//
// Run: npx tsx scripts/generate-seed-manifest.ts

import * as fs from 'fs';
import * as path from 'path';

type Row = Record<string, unknown>;

const root = path.join(__dirname, '..');
const seed = JSON.parse(
  fs.readFileSync(path.join(root, 'assets', 'seeds', 'initial-seed.json'), 'utf8'),
) as { tables: Record<string, Row[]> };

const t = seed.tables;

const exercisesByPiece = new Map<string, { id: string; updated_at: unknown }[]>();
for (const e of t.exercises ?? []) {
  const pid = String(e.piece_id);
  if (!exercisesByPiece.has(pid)) exercisesByPiece.set(pid, []);
  exercisesByPiece.get(pid)!.push({ id: String(e.id), updated_at: e.updated_at ?? null });
}

const pieces = (t.pieces ?? []).map((p) => ({
  id: String(p.id),
  updated_at: p.updated_at ?? null,
  // In the seed file source_uri/thumbnail_uri are stored as bare basenames of
  // the base64-embedded files; the seeder rewrote them to absolute sandbox
  // URIs at insert time. The basenames identify the files to delete.
  files: [p.source_uri, p.thumbnail_uri].filter(
    (v): v is string => typeof v === 'string' && v.length > 0,
  ),
  exercises: exercisesByPiece.get(String(p.id)) ?? [],
}));

const folders = (t.folders ?? []).map((f) => ({
  id: String(f.id),
  updated_at: f.updated_at ?? null,
}));

// practice_log.id is INTEGER PRIMARY KEY in SQLite — keep the ids numeric so
// the cleanup's IN (...) comparisons never depend on type coercion.
const practiceLogIds = (t.practice_log ?? []).map((r) => r.id);

const settings = (t.settings ?? []).map((s) => ({
  key: String(s.key),
  value_json: String(s.value_json),
}));

const out = `// GENERATED by scripts/generate-seed-manifest.ts — do not edit by hand.
//
// Fingerprint of the retired bundled starter seed (Ralph's April 2026 iPad
// export that older binaries planted into every fresh install). Used by
// lib/db/seedCleanup.ts to identify and remove starter rows that the device's
// user never touched. ids + updated_at stamps only; the full seed data lives
// in assets/seeds/initial-seed.json (kept in the repo, no longer bundled).

export type SeedPiece = {
  id: string;
  updated_at: number | null;
  files: string[];
  exercises: { id: string; updated_at: number | null }[];
};

export const SEED_PIECES: SeedPiece[] = ${JSON.stringify(pieces, null, 2)};

export const SEED_FOLDERS: { id: string; updated_at: number | null }[] = ${JSON.stringify(folders, null, 2)};

export const SEED_PRACTICE_LOG_IDS: number[] = ${JSON.stringify(practiceLogIds, null, 2)};

export const SEED_SETTINGS: { key: string; value_json: string }[] = ${JSON.stringify(settings, null, 2)};
`;

fs.writeFileSync(path.join(root, 'lib', 'db', 'seedManifest.ts'), out);
console.log(
  `Wrote lib/db/seedManifest.ts: ${pieces.length} pieces, ${folders.length} folders, ` +
    `${practiceLogIds.length} practice-log rows, ${settings.length} settings.`,
);
